/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Dialogue_02.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Dialogue_02: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Dialogue_02()
	{
		this.StartPassage = "BulletHeadIntro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: BulletHeadIntro

	void passage1_Init()
	{
		this.Passages[@"BulletHeadIntro"] = new StoryPassage(@"BulletHeadIntro", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("WHAT THE FUCK WAS THAT? THAT WASN'T A GRUE!!! I MEAN...WHAT THE HELL IS A GRUE, ANYWAY?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("AND...WHERE AM I? WHAT THE HELL IS GOING ON HERE?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I haven't quite figured that out yet.", "BHINTRO2", null);
		yield return lineBreak();
		yield return link("Uh, you're...talking to me?", "4THWALL", null);
		yield break;
	}


	// .............
	// #2: BHINTRO2

	void passage2_Init()
	{
		this.Passages[@"BHINTRO2"] = new StoryPassage(@"BHINTRO2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Yeah, well...you and me both pal! I just sort of...appeared here all of a sudden...wherever here is.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("It seems to be some kind of text adventure role-playing game featuring a turn based battle system", "BHINTRO3", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wait a sec, let's back up...", "BulletHeadIntro", null);
		yield break;
	}


	// .............
	// #3: 4THWALL

	void passage3_Init()
	{
		this.Passages[@"4THWALL"] = new StoryPassage(@"4THWALL", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("You see anybody else in here?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I don't see anybody, period", "BHSPRITE", null);
		yield return lineBreak();
		yield return link("No, I suppose not...so...who are you?", "BHINTRO4", null);
		yield break;
	}


	// .............
	// #4: BHINTRO3

	void passage4_Init()
	{
		this.Passages[@"BHINTRO3"] = new StoryPassage(@"BHINTRO3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Video game, huh? That sounds dumb.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I guess that depends on your point of view", "POV", null);
		yield return lineBreak();
		yield return link("You sound dumb.", "DUMB", null);
		yield break;
	}


	// .............
	// #5: BHSPRITE

	void passage5_Init()
	{
		this.Passages[@"BHSPRITE"] = new StoryPassage(@"BHSPRITE", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Ah, that's a little better...at least I'm not some nebulous disembodied narration now.  Wait a minute...what the fuck!? Why do I have a bucket on my head?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I think it's supposed to be a bullet. Seems like you're the main character in this video game.", "BHINTRO3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: POV

	void passage6_Init()
	{
		this.Passages[@"POV"] = new StoryPassage(@"POV", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Sure. Whatever.  Look...whatever this is, it's freaking me out a bit. Can we just get on with it? Get eaten by a Grue, or don't...I mean...whatever man, I just want to get out of here.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Maybe we can help each other out.", "HELP", null);
		yield return lineBreak();
		yield return link("Hahaha...no. I control you, we'll proceed as I see fit.", "CONTROL", null);
		yield break;
	}


	// .............
	// #7: DUMB

	void passage7_Init()
	{
		this.Passages[@"DUMB"] = new StoryPassage(@"DUMB", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Real mature. Dummy.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("This isn't getting us anywhere.", "BHINTRO3", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #8: BHINTRO4

	void passage8_Init()
	{
		this.Passages[@"BHINTRO4"] = new StoryPassage(@"BHINTRO4", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("I'm Bullethead.  Wait...what?  How do I even know this...I didn't even exist a second ago and now I'm introducing myself...Christ...well, I guess that's as good a name as any.  So yeah.  Bullethead. That's me.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Okay, so, uh... we go where from here?", "WORLDMAP1", null);
		yield return lineBreak();
		yield return link("I'm confused, can we start this coversation over again?", "BulletHeadIntro", null);
		yield break;
	}


	// .............
	// #9: WORLDMAP1

	void passage9_Init()
	{
		this.Passages[@"WORLDMAP1"] = new StoryPassage(@"WORLDMAP1", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("You emerge from the total darkness into a dimly lit clearing, surrounded on all sides by gnarled dead looking trees.  There's a tree stump in the center of the clearing with what appears to be a rusty hatchet embedded in it.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Grab the hatchet", "HATCHET1", null);
		yield return lineBreak();
		yield return link("approach the tree stump slowly", "HATCHET2", null);
		yield break;
	}


	// .............
	// #10: HELP

	void passage10_Init()
	{
		this.Passages[@"HELP"] = new StoryPassage(@"HELP", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return link("Placeholder Text", "WORLDMAP1", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #11: CONTROL

	void passage11_Init()
	{
		this.Passages[@"CONTROL"] = new StoryPassage(@"CONTROL", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return link("Placeholder Text", "WORLDMAP1", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #12: HATCHET1

	void passage12_Init()
	{
		this.Passages[@"HATCHET1"] = new StoryPassage(@"HATCHET1", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #13: HATCHET2

	void passage13_Init()
	{
		this.Passages[@"HATCHET2"] = new StoryPassage(@"HATCHET2", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}