/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: TheAdventuresofBulletHead.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @TheAdventuresofBulletHead: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@TheAdventuresofBulletHead()
	{
		this.StartPassage = "A Dark Place";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: A Dark Place

	void passage1_Init()
	{
		this.Passages[@"A Dark Place"] = new StoryPassage(@"A Dark Place", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"You can't see anything. It is entirely black in here, except for this text obviously...");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"EAST", @"EAST", null);
		yield return lineBreak();
		yield return link(@"WEST", @"WEST", null);
		yield return lineBreak();
		yield return link(@"NORTH", @"NORTH", null);
		yield return lineBreak();
		yield return link(@"SOUTH", @"SOUTH", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: EAST

	void passage2_Init()
	{
		this.Passages[@"EAST"] = new StoryPassage(@"EAST", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"You head east. There's nothing here yet.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"A Dark Place", @"A Dark Place", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: WEST

	void passage3_Init()
	{
		this.Passages[@"WEST"] = new StoryPassage(@"WEST", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"There's nothing here yet.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"A Dark Place", @"A Dark Place", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: NORTH

	void passage4_Init()
	{
		this.Passages[@"NORTH"] = new StoryPassage(@"NORTH", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text(@"It is still almost pitch black, but you think you can make out a small flickering light in the far distance.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Follow the light", @"Follow the light", null);
		yield return lineBreak();
		yield return link(@"A Dark Place", @"A Dark Place", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: SOUTH

	void passage5_Init()
	{
		this.Passages[@"SOUTH"] = new StoryPassage(@"SOUTH", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"There's nothing here yet. Don't get eaten by a grue!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"A Dark Place", @"A Dark Place", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Follow the light

	void passage6_Init()
	{
		this.Passages[@"Follow the light"] = new StoryPassage(@"Follow the light", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text(@"The light seems to be getting bigger as you move toward it. Suddenly, you hear some strange noises coming from both your left and right.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Go Left", @"Go Left", null);
		yield return lineBreak();
		yield return link(@"Go Right", @"Go Right", null);
		yield return lineBreak();
		yield return link(@"KeepFollowingtheLight", @"KeepFollowingtheLight", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: Go Left

	void passage7_Init()
	{
		this.Passages[@"Go Left"] = new StoryPassage(@"Go Left", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(@"The Light fades and it's pitch black again.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"ContinueintotheDarkness", @"ContinueintotheDarkness", null);
		yield return lineBreak();
		yield return link(@"Follow the light", @"Follow the light", null);
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: Go Right

	void passage8_Init()
	{
		this.Passages[@"Go Right"] = new StoryPassage(@"Go Right", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"The Light fades and it's pitch black again.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"ContinueintotheDarkness", @"ContinueintotheDarkness", null);
		yield return lineBreak();
		yield return link(@"Follow the light", @"Follow the light", null);
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: KeepFollowingtheLight

	void passage9_Init()
	{
		this.Passages[@"KeepFollowingtheLight"] = new StoryPassage(@"KeepFollowingtheLight", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text(@"You feel yourself suddenly falling into some kind of void!");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: ContinueintotheDarkness

	void passage10_Init()
	{
		this.Passages[@"ContinueintotheDarkness"] = new StoryPassage(@"ContinueintotheDarkness", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(@"You are attacked by a grue!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Attack", @"Attack", null);
		yield return lineBreak();
		yield return link(@"A Dark Place", @"A Dark Place", null);
		yield return text(@" ");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: Attack

	void passage11_Init()
	{
		this.Passages[@"Attack"] = new StoryPassage(@"Attack", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text(@"Double-click this passage to edit it.");
		yield return lineBreak();
		yield break;
	}


}